# Generated by Django 4.1.7 on 2023-04-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_employee_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_1', models.BooleanField()),
                ('monday_2', models.BooleanField()),
                ('monday_3', models.BooleanField()),
                ('tuesday_1', models.BooleanField()),
                ('tuesday_2', models.BooleanField()),
                ('tuesday_3', models.BooleanField()),
                ('wednesday_1', models.BooleanField()),
                ('wednesday_2', models.BooleanField()),
                ('wednesday_3', models.BooleanField()),
                ('thursday_1', models.BooleanField()),
                ('thursday_2', models.BooleanField()),
                ('thursday_3', models.BooleanField()),
                ('friday_1', models.BooleanField()),
                ('friday_2', models.BooleanField()),
                ('friday_3', models.BooleanField()),
                ('saturday_1', models.BooleanField()),
                ('saturday_2', models.BooleanField()),
                ('saturday_3', models.BooleanField()),
                ('sunday_1', models.BooleanField()),
                ('sunday_2', models.BooleanField()),
                ('sunday_3', models.BooleanField()),
            ],
        ),
    ]
