# Generated by Django 4.1.7 on 2023-04-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyShiftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_1', models.IntegerField()),
                ('monday_2', models.IntegerField()),
                ('monday_3', models.IntegerField()),
                ('tuesday_1', models.IntegerField()),
                ('tuesday_2', models.IntegerField()),
                ('tuesday_3', models.IntegerField()),
                ('wednesday_1', models.IntegerField()),
                ('wednesday_2', models.IntegerField()),
                ('wednesday_3', models.IntegerField()),
                ('thursday_1', models.IntegerField()),
                ('thursday_2', models.IntegerField()),
                ('thursday_3', models.IntegerField()),
                ('friday_1', models.IntegerField()),
                ('friday_2', models.IntegerField()),
                ('friday_3', models.IntegerField()),
                ('saturday_1', models.IntegerField()),
                ('saturday_2', models.IntegerField()),
                ('saturday_3', models.IntegerField()),
                ('sunday_1', models.IntegerField()),
                ('sunday_2', models.IntegerField()),
                ('sunday_3', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday_3',
            field=models.BooleanField(default=False),
        ),
    ]
