# Generated by Django 4.1.7 on 2023-05-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_weeklyshiftplan_alter_schedule_friday_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='scheduler.employee'),
            preserve_default=False,
        ),
    ]
