# Generated by Django 4.1.7 on 2023-05-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_schedule_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='employee',
        ),
    ]
