# Generated by Django 4.1.7 on 2023-05-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_remove_schedule_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.employee'),
        ),
    ]
