# Generated by Django 4.1.7 on 2023-05-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_schedule_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
