# Generated by Django 4.1.7 on 2023-05-17 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_calenderweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='calender_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.calenderweek'),
        ),
    ]
