# Generated by Django 4.1.7 on 2023-05-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_schedule_calender_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyshiftplan',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
