# Generated by Django 4.1.7 on 2023-05-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_weeklyshiftplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=12)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler.employee')),
            ],
        ),
    ]
