# Generated by Django 4.1.7 on 2023-05-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='my_field',
        ),
        migrations.AddField(
            model_name='preferences',
            name='friday_1',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='friday_2',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='friday_3',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='monday_1',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='monday_2',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='monday_3',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='saturday_1',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='saturday_2',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='saturday_3',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='sunday_1',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='sunday_2',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='sunday_3',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='thursday_1',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='thursday_2',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='thursday_3',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='tuesday_1',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='tuesday_2',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='tuesday_3',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='wednesday_1',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='wednesday_2',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='wednesday_3',
            field=models.CharField(choices=[('OPTION_ONE', 'Gut'), ('OPTION_TWO', 'Würde gehen, aber nicht gut'), ('OPTION_THREE', 'Gar nicht')], default='OPTION_ONE', max_length=20),
        ),
    ]
